'use client';
import {useEffect,useState} from 'react'; import {useTheme} from 'next-themes';
type Me={id:string;hakiId:string;username:string;displayName:string;hakiIdVisible:boolean}; type P={id:string;text:string;createdAt:string;author:any;_count:any;likes:any[];reposts:any[]};
export default function Home(){const [me,setMe]=useState<Me|null|undefined>();const [posts,setPosts]=useState<P[]>([]);const [text,setText]=useState('');const [toast,setToast]=useState('');const {theme,setTheme}=useTheme();
 async function load(){const m=await fetch('/api/me').then(r=>r.json());setMe(m);if(m){const p=await fetch('/api/posts').then(r=>r.json());setPosts(p)}} useEffect(()=>{load()},[]);
 async function act(url:string,method='POST',body?:any){const r=await fetch(url,{method,headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok){setToast(j.error||'حدث خطأ');return null}return j}
 async function publish(){if(!text.trim())return;await act('/api/posts','POST',{text});setText('');setToast('تم النشر');load()}
 if(me===undefined)return <main className="shell"><p>جاري التحميل…</p></main>; if(!me)return <Auth onDone={load}/>;
 return <main className="shell"><header className="top"><div className="logo">حَكي</div><div className="nav"><a className="btn" href="#">الرئيسية</a><a className="btn" href="#">اكتشف</a><a className="btn" href="#">الإشعارات</a><a className="btn" href="#">الرسائل</a><a className="btn primary" href="/camry">CAMRY</a><button className="btn" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'☀️ فاتح':'🌙 داكن'}</button><button className="btn" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});load()}}>خروج</button></div></header><div className="grid"><main><section className="card"><h2>وش حاب تحكي؟</h2><textarea className="field" value={text} onChange={e=>setText(e.target.value)} maxLength={5000} placeholder="اكتب منشورك…"/><div className="row between"><span className="muted">{text.length}/5000</span><button className="btn primary" onClick={publish}>نشر</button></div></section>{posts.map(p=><article className="card" key={p.id}><div><b>{p.author.displayName}</b> <span className="muted">@{p.author.username}</span></div><p style={{fontSize:19,lineHeight:1.8}}>{p.text}</p><div className="actions"><button className="action" onClick={()=>act(`/api/posts/${p.id}/like`).then(load)}>♥ {p._count.likes}</button><button className="action" onClick={async()=>{const c=prompt('التعليق');if(c)await act(`/api/posts/${p.id}/comment`,'POST',{text:c});load()}}>◌ {p._count.comments}</button><button className="action" onClick={()=>act(`/api/posts/${p.id}/repost`).then(load)}>↻ {p._count.reposts}</button></div></article>)}</main><aside><section className="card"><h3>حسابي</h3><b>{me.displayName}</b><p className="muted">@{me.username}</p>{me.hakiIdVisible&&<p>معرّف حَكي: <b>{me.hakiId}</b></p>}</section><section className="card"><h3>الرائج</h3><p className="tag">#السعودية</p><p className="tag">#حَكي</p><p className="tag">#تقنية</p></section></aside></div>{toast&&<div className="toast">{toast}</div>}</main>}
function Auth({onDone}:{onDone:()=>void}){const [mode,setMode]=useState<'login'|'register'>('register');const [v,setV]=useState({displayName:'',username:'',email:'',password:''});const [err,setErr]=useState('');async function submit(){const url=mode==='register'?'/api/auth/register':'/api/auth/login';const body=mode==='register'?v:{email:v.email,password:v.password};const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){setErr(j.error||'خطأ');return}onDone()}return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:20}}><section className="card" style={{maxWidth:480,width:'100%'}}><h1 className="logo">حَكي</h1><h2>{mode==='register'?'إنشاء حساب':'تسجيل الدخول'}</h2>{mode==='register'&&<input className="field" placeholder="الاسم" value={v.displayName} onChange={e=>setV({...v,displayName:e.target.value})}/>} {mode==='register'&&<input className="field" placeholder="اسم المستخدم بالإنجليزية" value={v.username} onChange={e=>setV({...v,username:e.target.value})}/>}<input className="field" placeholder="البريد الإلكتروني" value={v.email} onChange={e=>setV({...v,email:e.target.value})}/><input className="field" type="password" placeholder="كلمة المرور" value={v.password} onChange={e=>setV({...v,password:e.target.value})}/>{err&&<p style={{color:'#ef4444'}}>{err}</p>}<button className="btn primary" style={{width:'100%'}} onClick={submit}>{mode==='register'?'إنشاء الحساب':'دخول'}</button><button className="btn" style={{marginTop:10,width:'100%'}} onClick={()=>setMode(mode==='register'?'login':'register')}>{mode==='register'?'لدي حساب بالفعل':'إنشاء حساب جديد'}</button></section></main>}
