'use client';
import {useEffect,useState} from 'react';

type Data={users:any[];posts:any[];audit:any[]};
export default function Camry(){
 const [admin,setAdmin]=useState<any|undefined>(); const [data,setData]=useState<Data|null>(null); const [tab,setTab]=useState('dashboard'); const [preview,setPreview]=useState<any>(null); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [err,setErr]=useState('');
 const load=async()=>{const m=await fetch('/api/camry/me').then(r=>r.json());setAdmin(m);if(m){const r=await fetch('/api/camry/users');if(r.ok)setData(await r.json())}};
 useEffect(()=>{load()},[]);
 async function login(){setErr('');const r=await fetch('/api/camry/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})});const j=await r.json();if(!r.ok){setErr(j.error||'فشل الدخول');return}await load()}
 async function action(id:string,action:'hide'|'delete'){const r=await fetch(`/api/camry/content/${id}/action`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action})});if(!r.ok){const j=await r.json();setErr(j.error||'تعذر تنفيذ العملية');return}await load()}
 async function previewUndo(id:string){const r=await fetch(`/api/camry/audit/${id}/undo`);const j=await r.json();if(!r.ok){setErr(j.error||'تعذر المعاينة');return}setPreview(j)}
 async function undo(id:string){const r=await fetch(`/api/camry/audit/${id}/undo`,{method:'POST'});if(!r.ok){const j=await r.json();setErr(j.error||'تعذر الاستعادة');return}await load()}
 if(admin===undefined)return <main className="shell"><p>جاري التحقق…</p></main>;
 if(!admin)return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:20}}><section className="card" style={{maxWidth:480,width:'100%'}}><div className="logo">CAMRY</div><p className="muted">دخول مستقل لمركز تشغيل حَكي</p><input className="field" placeholder="البريد الإلكتروني" value={email} onChange={e=>setEmail(e.target.value)}/><input className="field" type="password" placeholder="كلمة المرور" value={password} onChange={e=>setPassword(e.target.value)}/>{err&&<p style={{color:'#ef4444'}}>{err}</p>}<button className="btn primary" style={{width:'100%'}} onClick={login}>دخول CAMRY</button><a className="btn" style={{display:'block',marginTop:10,textAlign:'center'}} href="/">العودة للمنصة</a></section></main>;
 return <main className="shell"><header className="top"><div><div className="logo">CAMRY</div><div className="muted">{admin.name} · مركز تشغيل حَكي</div></div><div className="nav"><a className="btn" href="/">العودة</a><button className="btn" onClick={async()=>{await fetch('/api/camry/auth/logout',{method:'POST'});setAdmin(null);setData(null)}}>خروج</button></div></header>
 <nav className="adminNav">{[['dashboard','نظرة عامة'],['users','المستخدمون'],['content','المحتوى'],['audit','سجل العمليات'],['team','الفريق'],['roles','الأدوار'],['settings','الإعدادات']].map(([k,l])=><button className={`btn ${tab===k?'primary':''}`} key={k} onClick={()=>setTab(k)}>{l}</button>)}</nav>{err&&<div className="card" style={{color:'#ef4444'}}>{err}</div>}
 {tab==='dashboard'&&<div className="stats">{[['المستخدمون',data?.users.length||0],['المنشورات',data?.posts.length||0],['العمليات',data?.audit.length||0]].map(x=><div className="card stat" key={String(x[0])}><span className="muted">{x[0]}</span><strong>{x[1]}</strong></div>)}</div>}
 {tab==='users'&&<section className="card"><h2>المستخدمون</h2>{(data?.users||[]).map((u:any)=><div key={u.id} style={{padding:'12px 0',borderBottom:'1px solid var(--border)'}}><b>{u.displayName}</b> · @{u.username} · Haki ID {u.hakiId} · {u.status}</div>)}</section>}
 {tab==='content'&&<section className="card"><h2>المحتوى</h2>{(data?.posts||[]).map((p:any)=><div key={p.id} className="row between" style={{padding:12,borderBottom:'1px solid var(--border)'}}><span>#{p.id} · {p.text}</span><span><button className="btn" onClick={()=>action(p.id,'hide')}>إخفاء</button> <button className="btn danger" onClick={()=>action(p.id,'delete')}>حذف</button></span></div>)}</section>}
 {tab==='audit'&&<section className="card"><h2>سجل العمليات والتراجع</h2>{(data?.audit||[]).map((a:any)=><div key={a.id} style={{padding:12,borderBottom:'1px solid var(--border)'}}><b>{a.action}</b> · {a.targetType} {a.targetId}<div className="muted">{new Date(a.createdAt).toLocaleString('ar-SA')}</div>{a.targetType==='post'&&<button className="btn" style={{marginTop:8}} onClick={()=>previewUndo(a.id)}>معاينة الحالة السابقة</button>}</div>)}</section>}
 {['team','roles','settings'].includes(tab)&&<section className="card"><h2>{tab==='team'?'فريق CAMRY':tab==='roles'?'الأدوار والصلاحيات':'إعدادات المنصة'}</h2><p className="muted">الوحدة موجودة ضمن بنية CAMRY وقابلة للتوسع وربط الصلاحيات والعمليات الفعلية.</p></section>}
 {preview&&<div className="modal" onClick={()=>setPreview(null)}><div className="modalbox" onClick={e=>e.stopPropagation()}><h2>معاينة قبل الاستعادة</h2><p><b>{preview.post?.author?.displayName}</b> @{preview.post?.author?.username}</p><p style={{fontSize:19,lineHeight:1.8}}>{preview.post?.text||'المحتوى غير متوفر'}</p><p className="muted">الحالة الحالية: {preview.post?.deletedAt?'محذوف':preview.post?.hiddenAt?'مخفي':'ظاهر'}</p><div className="row"><button className="btn" onClick={()=>setPreview(null)}>إلغاء</button><button className="btn primary" onClick={async()=>{await undo(preview.id);setPreview(null)}}>تأكيد الاستعادة</button></div></div></div>}
 </main>
}
